mingw-w64 support: Patch TransformAxis.h: Modify code
Fix error on mingw-w64 during header preprocessing:

  Simulation\SimbodyEngine\TransformAxis.h:86:1: warning: missing '}'
  error: unable to preprocess Simulation\SimbodyEngine\cxx{CustomJoint.cpp}@...

Caused by GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84583.